# The west manifest file (west.yml) for npmx-zephyr.

manifest:
  defaults:
    remote: NordicSemiconductor

  remotes:
    - name: NordicSemiconductor
      url-base: https://github.com/NordicSemiconductor
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v3.3.0
      import: true
    - name: npmx
      revision: v0.6.0
      path: modules/npmx
    - name: sdk-nrfxlib
      remote: nrfconnect
      revision: v2.4.0-rc1
      path: modules/nrfxlib
